### ISSUE TITLE
Step numbering

### ISSUE THREAD

**Issue by KRiedmiller** [graeter-group/kimmdy#177]
```
1  eq
2  pull
3  hat
3  homolysis
5  recipe
5  relax
6  eq
7  pull
8  hat
8  homolysis
10 recipe
10 relax
11 eq
12 pull
13 hat
13 homolysis
15 recipe
15 relax
...
```

From sequence
```
sequence:
  - equilibrium
  - mult: 3
    tasks:
      - pull
      - reactions
      - equilibrium
```
